config/routes.rb
GpenApp::Application.routes.draw do

  
  resources :searchonprojects

  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/profile', to: 'static_pages#profile'
  match '/create_org', to: 'static_pages#create_org'
  match '/browse_orgs', to: 'static_pages#browse_orgs'
  match '/list_orgs', to: 'static_pages#list_orgs'
  match '/org_profile', to: 'static_pages#org_profile'

  match '/create_job', to: 'static_pages#create_job'
  match '/browse_jobs', to: 'static_pages#browse_jobs'
  match '/list_jobs', to: 'static_pages#list_jobs'
  match '/single_job', to: 'static_pages#single_job'
  match '/single_project', to: 'static_pages#single_project'

  resources :jobs do
    get :resetcookies
  end

  resources :organizations do
    put :approve
    put :renew_three
    post :renew
    get :resetcookies
    member do
      get :contacthistories 
    end
  end

  resources :jobenrollments, only: [:create, :destroy]
  
  resources :projects do
    get :resetcookies
  end

  resources :projectenrollments, only: [:create, :destroy]

  resources :users do
    member do
      get :jobs, :projects, :organizations
      match '/confirm/:token' => 'users#confirm', :as => :confirm
    end
  end

  resources :contacthistories, only: [:new, :create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/resetpswd', to: 'users#resetpswd'

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @user = User.new
    #@latest_orgs = Organization.find(:all, :order => "updated_at desc", :limit => 5)
    @latest_orgs = Organization.where('approved = ? AND end_date > ?', true, Date.today)
                    .order("created_at DESC")
                    .limit(5)

    #@latest_jobs = Job.find(:all, :order => "updated_at desc", :limit => 5)
    @latest_jobs = Job.joins(:organization)
                      .where('organizations.approved = ? AND organizations.end_date > ?', true, Date.today)
                      .order("jobs.created_at DESC")
                      .limit(5)

    #@latest_projects = Project.find(:all, :order => "updated_at desc", :limit => 5)
    @latest_projects = Project.includes(:organization)
                              .where('(organizations.approved = ? AND organizations.end_date > ?) OR organization_id is null', true, Date.today)
                              .order("projects.created_at DESC")
                              .limit(5)

  end

  def about
  end

  def profile
  end

  def create_org
  end

  def browse_orgs
  end

  def org_profile
  end

  def list_orgs
  end

  def create_job
  end

  def browse_jobs
  end

  def list_jobs
  end

  def single_job
  end

  def single_project
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'Help') %>

<div class="well">
	<h1>About GPEN</h1>
	<p style="align:justify">
	The Databases of the Greater Philadelphia Environmental Network - a.k.a. "GPEN" - were created in 2005 by Sherry Riesner with seed funding from the Environmental Leadership Program Activity Fund. Because of the intrinsic value of the information contained in these tables we decided to rehost the GPEN Databases with more up-to-date, easy to use technology on the <%= link_to "PhillyEcoCity.com", "http://www.phillycocity.com" %> platform.
	</p>

	<p>
	The GPEN Databases help connect Enviromental and Sustainability related nonprofits, community-based organizations, businesses and professional groups, educational institutions, government agencies, and the general public in our region. The goal of the GPEN Databases is to fill an environmental information gap in our metropolitan area, and by doing so, dramatically increase individual involvement, and collaborations in our local environmental community.
	</p>

	<p>
	Our vision for PhillyEcoCity is to use the tools of information technology such as the GPEN databases to foster collaborations at the neighborhood, municipal, city, and county levels and increase significantly partnerships, coalitions, and visibility for environmental issues and initiatives.
	</p>
	<p>
	The GPEN Databases help increase volunteerism, inspire new projects, and feature educational and employment opportunities. Improved environmental communication will not only enhance the activities that relate to our natural world, but also our community and economic development and ultimately the health and quality of life of the region
	</p>

</div>

app/views/static_pages/browse_jobs.html.erb
<ul class="breadcrumb">
        <li>
          <a href="#">Home</a> <span class="divider">/</span>
        </li>
        <li class="active">Jobs</li>
      </ul>

<div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            
            <ul class="nav nav-list">
              <h3>Filters</h3>
              <li class="nav-header">By County</li>
              <li><a href="#">Bucks</a></li>
              <li><a href="#">Chester</a></li>
              <li><a href="#">Delaware</a></li>
              <li class="active"><a href="#">Montgomery</a></li>
              <li><a href="#">Philadelphia</a></li>
              <li class="active"><a href="#">Harrisburg</a></li>
              <li class="nav-header">By Type</li>
              <li><a href="#">Transportation</a></li>
              <li><a href="#">Energy</a></li>
              <li><a href="#">Housing</a></li>
              <li><a href="#">Food</a></li>
              <li><a href="#">Healthcare</a></li>
              <li><a href="#">Waste Management</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <div class="hero-unit">
            <h1>Green Jobs</h1>
            <p>We are proud to say that we have 1,019 (and counting!) green organizations listed on our website. Use the filters to the left or the search bar below to find organizations.</p>
            <form class="form-search form-big-search">
              <input type="text" class="big-search-query">
              <button type="submit" class="btn btn-primary btn-big-search pull-right">Search</button>
            </form>

          </div>
          <div class="row-fluid">
            <h6>Latest Jobs</h6>
          </div>
          <div class="row-fluid">
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
          </div><!--/row-->
          <div class="row-fluid">
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
          </div><!--/row-->
        </div><!--/span-->
      </div><!--/row-->

app/views/static_pages/browse_orgs.html.erb
<ul class="breadcrumb">
        <li>
          <a href="#">Home</a> <span class="divider">/</span>
        </li>
        <li class="active">Organizations</li>
      </ul>

<div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            
            <ul class="nav nav-list">
              <h3>Filters</h3>
              <li class="nav-header">By County</li>
              <li><a href="#">Bucks</a></li>
              <li><a href="#">Chester</a></li>
              <li><a href="#">Delaware</a></li>
              <li class="active"><a href="#">Montgomery</a></li>
              <li><a href="#">Philadelphia</a></li>
              <li class="active"><a href="#">Harrisburg</a></li>
              <li class="nav-header">By Type</li>
              <li><a href="#">Transportation</a></li>
              <li><a href="#">Energy</a></li>
              <li><a href="#">Housing</a></li>
              <li><a href="#">Food</a></li>
              <li><a href="#">Healthcare</a></li>
              <li><a href="#">Waste Management</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <div class="hero-unit">
            <h1>Green Organizations</h1>
            <p>We are proud to say that we have 1,019 (and counting!) green organizations listed on our website. Use the filters to the left or the search bar below to find organizations.</p>
            <form class="form-search form-big-search">
              <input type="text" class="big-search-query">
              <button type="submit" class="btn btn-primary btn-big-search pull-right">Search</button>
            </form>

          </div>
          <div class="row-fluid">
            <h6>Latest Organizations</h6>
          </div>
          <div class="row-fluid">
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
          </div><!--/row-->
          <div class="row-fluid">
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
          </div><!--/row-->
        </div><!--/span-->
      </div><!--/row-->

app/views/static_pages/home.html.erb
      <div class="row">
        
        <div class="span9">
          <div class="hero-unit">
            <h1>Welcome to the GPEN Database </h1>
            <h2>Powered by <%= link_to "PhillyEcoCity", "http://www.phillyecocity.com" %></h2>
            <p>The GPEN Databases are an Internet resource for Environmental and Sustainability related Organizations, "Green" Jobs and "Green" Volunteer Opportunities in the Greater Philadelphia region.</p>
            <p><a href="<%= about_path %>" class="btn btn-success btn-large">Learn more &raquo;</a></p>
          </div>
        </div><!--/span-->
        <div class="span3">
        	<div class="well">
		  		

            <% if signed_in? %>

              <h6>Logged in as:</h6>
              <h3><%= current_user.fname %> <%= current_user.lname %></h3>
              
              <%= link_to "Sign Out", signout_path, method: "delete", class: "btn btn-signup" %>


            <% else %>
              <h6>GPEN Member Login</h6>
               <%= form_for(:session, :url => sessions_path) do |f| %>
                  <%= f.text_field :email, class: "login-field", placeholder: "Email" %>
                  <%= f.password_field :password, class: "login-field", placeholder: "Password" %>
                  <%= f.submit "Sign In", class: "btn btn-primary" %>

              <% end %>

              <span class="forgot-password"><%= link_to "Forgot your password?", resetpswd_path, method: 'get' %></span>

               <hr>
               <h6>Not a Member?</h6>
               <a class="modal-btn btn btn-signup" data-toggle="modal" href="#signup-modal" >Sign Up, It's Free!</a>
            <% end %>


          
			</div> <!--/well-->
        </div><!--/span-->
      </div><!--/row-->
      <div class="row">
            <div class="span4">
              <div class="well">
              <h2><%= link_to "Organizations", organizations_path, :title => "Browse All Green Organizations", :rel => "tooltip" %></h2>
              <div class="entity-description">
                <!-- old <p>The GPEN Organization Database is a key resource for everyone looking to connect to Environmental and Sustainability related non-profits or for profit Organizations in the Greater Philadelphia area. If your Organization or Company is not already in the GPEN Database, please create an entry for it. You must create an entry for your for profit or not for profit organization in the GPEN Organization database before being able to post a Green Job.</p> -->

                <p>The GPEN Organization Database is a key resource for everyone looking to connect to Environmental and Sustainability related non-profits or for-profit organizations in the Greater Philadelphia area. If your organization is not already in the Organization Database, please create an entry for it.</p>
              </div>
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                          <th>Latest Organizations</th>
                        </tr>
                      </thead>
                    <tbody>


                      <% @latest_orgs.each do |organization| %>
                        <tr>
                          <td>
                            <h4><%= link_to(organization.name, organization, :class => "home-org-popover", :rel => "popover", "data-original-title" => organization.name, "data-content" => truncate(organization.description, :length => 100, :omission => '...')) %></h4>

                            <p>Joined <%= time_ago_in_words(organization.created_at) %> ago</p>

                          </td>
                        </tr>
                      <% end %>

                      

                    </tbody>
                  </table>
                </div><!--/well-->
            </div><!--/span-->
            <div class="span4">
              <div class="well">
              <h2><%= link_to "Jobs", jobs_path, :title => "Browse All Green Jobs", :rel => "tooltip" %></h2>
              <div class="entity-description">
                <!-- old <p>The GPEN Jobs Database on PhillyEcoCity is the place to post your Green Jobs or to search for available Green Jobs in the Philadelphia Metropolitan area. To post a green job for your profit or not for profit organization you must first create an entry in the Organization GPEN Database.</p>-->

                <p>The GPEN Job Database is the place to post your Green Jobs or to search for available Green Jobs in the Philadelphia metropolitan area. To post a green job for your profit or not for profit organization your organization must first be listed in the Organization Database.</p>
              </div>
              <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                          <th>Latest Jobs</th>
                        </tr>
                      </thead>
                    <tbody>


                      <% @latest_jobs.each do |job| %>
                        <tr>
                          <td>
                            <h4><%= link_to(job.title, job, :class => "home-org-popover", :rel => "popover", "data-original-title" => job.title, "data-content" => truncate(job.description, :length => 100, :omission => '...')) %></h4>

                            <p>Posted <%= time_ago_in_words(job.created_at) %> ago</p>

                          </td>
                        </tr>
                      <% end %>

                      

                    </tbody>
                  </table>

              </div><!--/well-->
            </div><!--/span-->
            <div class="span4">
              <div class="well">
              <h2><%= link_to "Projects", projects_path, :title => "Browse All Green Projects", :rel => "tooltip" %></h2>
              <div class="entity-description">
                <!-- old <p>The GPEN Project Database on PhillyEcocity is the place to advertise your Organization's volunteer days or post the workday projects you are yourself organizing. Anyone can post a volunteering opportunity or a workday project. If you represent an organization, please login to your Organization account first. If you represent yourself or your group of neighbors or friends, start by creating a profile for yourself in the GPEN Database.</p> -->

                <p>The GPEN Project Database is the place to advertise your Organization's volunteer days or post workday projects that you are yourself organizing. Any registered user post a volunteering opportunity or a workday project, and any registered user can join them.</p>
              </div>
              <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                          <th>Latest Projects</th>

                        </tr>

      
                      </thead>
                    <tbody>


                      <% @latest_projects.each do |project| %>
                        <tr>
                          <td>
                            <h4><%= link_to(project.title, project, :class => "home-org-popover", :rel => "popover", "data-original-title" => project.title, "data-content" => truncate(project.proj_desc, :length => 100, :omission => '...')) %></h4>

                            <p>Posted <%= time_ago_in_words(project.created_at) %> ago</p>

                          </td>
                        </tr>
                      <% end %>

                      

                    </tbody>
                  </table>
              </div><!--/well-->
            </div><!--/span-->
       </div><!--/row-->


<% if !signed_in? %>
<div id="signup-modal" class="modal hide fade">
    <div class="modal-header">
      <a class="close" data-dismiss="modal" >&times;</a>
      <h3>Sign Up for a New Account</h3>
    </div>
    <div class="modal-body">
      <%= form_for(@user, :html => { :class => "form-horizontal" } ) do |f| %>
        <fieldset>
          <div class="control-group">
            <%= f.label :fname, "First Name", class: "control-label" %>
            <div class="controls">
              <%= f.text_field :fname, class: "input-xlarge" %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :lname, "Last Name", class: "control-label" %>
            <div class="controls">
              <%= f.text_field :lname, class: "input-xlarge" %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :email, class: "control-label" %>
            <div class="controls">
              <%= f.text_field :email, class: "input-xlarge" %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :phone, class: "control-label" %>
            <div class="controls">
              <%= f.text_field :phone, class: "input-xlarge" %>
            </div>
          </div>


          <div class="control-group">
            <%= f.label :birth_date, class: "control-label" %>
            <div class="controls">
              <%= date_select 'user', "birth_date", {:start_year => Date.today.year-100, :end_year => Date.today.year}, {class: "span1"} %>
            </div>
          </div>

          <div class="control-group">
          <%= f.label :bio, class: "control-label" %>
          <div class="controls">
            <%= f.text_area :bio, :rows => 3, class: "input-xlarge" %>
                <p class="help-block">Tell us about yourself: who are you and what are your passions? What are you involved with in Philadelphia?</p>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :website, class: "control-label" %>
          <div class="controls">
            <div class="input-prepend">
                <%= f.text_field :website, class: "span2" %>
              </div>
              <p class="help-block">Please copy-paste the full website URL : </p>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :facebook, class: "control-label" %>
          <div class="controls">
            
            
            <div class="input-prepend">
                <span class="add-on">facebook.com/</span><%= f.text_field :facebook,class: "span2", placeholder: "Facebook Handle" %>
              </div>
              <p class="help-block">Please only type in your profile name for Facebook, not the entire URL.</p>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :twitter, class: "control-label" %>
          <div class="controls">
            <div class="input-prepend">
                <span class="add-on">twitter.com/</span><%= f.text_field :twitter,class: "span2", placeholder: "Twitter Handle" %>
              </div>
            <p class="help-block">Please only type in your profile name for Twitter, not the entire URL.</p>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :linkedin, class: "control-label" %>
          <div class="controls">
            

            <div class="input-prepend">
                <span class="add-on">linkedin.com/in/</span><%= f.text_field :linkedin,class: "span2", placeholder: "LinkedIn Handle" %>
              </div>
            <p class="help-block">Please only type in your profile name for LinkedIn, not the entire URL.</p>
          </div>
        </div>


          <div class="control-group">
            <%= f.label :password, class: "control-label" %>
            <div class="controls">
              <%= f.password_field :password, class: "input-xlarge" %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :password_confirmation, "Confirmation", class: "control-label" %>
            <div class="controls">
              <%= f.password_field :password_confirmation, class: "input-xlarge" %>
            </div>
          </div>

          <div style="display:none">
            <%= f.password_field :botfisher, class: "input-xlarge", placeholder: "parapapapa" %>
          </div>

        </fieldset>
      
    </div>
    <div class="modal-footer">
      <%= f.submit "Create an Account", class: "btn btn-primary" %>
      <a href="#" class="btn" data-dismiss="modal">Close</a>
      
      
    </div>
    <% end %>
  </div>
<% end %>

app/views/static_pages/single_project.html.erb
    <ul class="breadcrumb">
        <li>
          <a href="#">Home</a> <span class="divider">/</span>
        </li>
        <li>
          <a href="<%= projects_path %>">Projects</a> <span class="divider">/</span>
        </li>
        <li class="active">Woodland Cemetery Clean-Up Day</li>
      </ul>



      <div class="row">
         <div class="span3">
          <div class="alert alert-info fade in">
            <a class="close" data-dismiss="alert">×</a>
              <h4 class="alert-heading">More People Needed!</h4>
              <p>This project has 4 of 20 people so far.</p>
              

              <p><div class="progress progress-success progress-striped active">
                <div class="bar" style="width: 45%"></div></div></p>

              <p><button class="btn btn-mini btn-success">Join</button>
                <button class="btn btn-mini">Back to Projects</button>
              </p>
              
            
            
          </div>
          <div class="well">
            <h6>Posted By</h6>
            <p><%= link_to "Woodland Cemetery", '#' %></p>
            <h6>Posted</h6><p>3 days ago</p>


            <h6>People Coming</h6>
            
            <%= link_to image_tag("profile/2.jpeg", :class => "profile-icon", :size => "30x30"), '#', :title => "jbroglie", :rel => "tooltip" %>
              <%= link_to image_tag("profile/3.jpeg", :class => "profile-icon", :size => "30x30"), '#', :title => "mhighland", :rel => "tooltip" %>
              <%= link_to image_tag("profile/4.jpeg", :class => "profile-icon", :size => "30x30"), '#', :title => "aminamina", :rel => "tooltip" %>
              <%= link_to image_tag("profile/1.jpeg", :class => "profile-icon", :size => "30x30"), '#', :title => "jsapriel", :rel => "tooltip" %>

              <%= link_to image_tag("profile/2.jpeg", :class => "profile-icon", :size => "30x30"), '#', :title => "jbroglie", :rel => "tooltip" %>
              <%= link_to image_tag("profile/3.jpeg", :class => "profile-icon", :size => "30x30"), '#', :title => "mhighland", :rel => "tooltip" %>
              <%= link_to image_tag("profile/4.jpeg", :class => "profile-icon", :size => "30x30"), '#', :title => "aminamina", :rel => "tooltip" %>
              <%= link_to image_tag("profile/1.jpeg", :class => "profile-icon", :size => "30x30"), '#', :title => "jsapriel", :rel => "tooltip" %>

              <%= link_to image_tag("profile/2.jpeg", :class => "profile-icon", :size => "30x30"), '#', :title => "jbroglie", :rel => "tooltip" %>
              <%= link_to image_tag("profile/3.jpeg", :class => "profile-icon", :size => "30x30"), '#', :title => "mhighland", :rel => "tooltip" %>
              <%= link_to image_tag("profile/4.jpeg", :class => "profile-icon", :size => "30x30"), '#', :title => "aminamina", :rel => "tooltip" %>
              <%= link_to image_tag("profile/1.jpeg", :class => "profile-icon", :size => "30x30"), '#', :title => "jsapriel", :rel => "tooltip" %>

            <hr>
            <div class="btn-group">
              <button class="btn btn-primary">Admin Actions</button>
              <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
              <ul class="dropdown-menu">
                <li><a href="#">Edit Job</a></li>
                <li class="divider"></li>
                
                <li><a href="#">Delete Job</a></li>
              </ul>
            </div>

          </div> <!--/well-->
        </div><!--/span-->
        <div class="span9">
          
          <div class="row">
            <div class="span9">
              <div class="hero-unit">
                
                <h1>Woodland Cemetery Clean-Up Day</h1>
                <p>Sunday, April 29, 2012 from 4PM-6PM</p>
                <hr>

                <h6>Description</h6>

                <p>Turpis sit montes nisi adipiscing ultrices, mattis vel proin urna ac nec. Tortor augue porta? Est sagittis, dis, hac adipiscing, ridiculus penatibus placerat non cras augue tristique rhoncus! Lorem nec auctor hac! Aliquet, arcu non, penatibus sed scelerisque auctor elementum, non amet? A amet porta aenean ac parturient, elementum odio? Mus amet? Amet porttitor nisi lacus! Nisi purus? Nisi, pulvinar.</p>


                <h6>Minimum Age</h6>
                <p>None</p>
                
                <h6>Address</h6>
                
                <p>
                    4001 Woodland Avenue<br>
                    Philadelphia, PA 19104

                </p>
                <hr>
                <button class="btn btn-large btn-success">Join Project</button>
        <button class="btn btn-large">Back to Projects</button></td>

              </div>

            </div>
          </div>

        </div><!--/span-->

      </div><!--/row-->