config/routes.rb
GpenApp::Application.routes.draw do

  
  resources :searchonprojects

  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/profile', to: 'static_pages#profile'
  match '/create_org', to: 'static_pages#create_org'
  match '/browse_orgs', to: 'static_pages#browse_orgs'
  match '/list_orgs', to: 'static_pages#list_orgs'
  match '/org_profile', to: 'static_pages#org_profile'

  match '/create_job', to: 'static_pages#create_job'
  match '/browse_jobs', to: 'static_pages#browse_jobs'
  match '/list_jobs', to: 'static_pages#list_jobs'
  match '/single_job', to: 'static_pages#single_job'
  match '/single_project', to: 'static_pages#single_project'

  resources :jobs do
    get :resetcookies
  end

  resources :organizations do
    put :approve
    put :renew_three
    post :renew
    get :resetcookies
    member do
      get :contacthistories 
    end
  end

  resources :jobenrollments, only: [:create, :destroy]
  
  resources :projects do
    get :resetcookies
  end

  resources :projectenrollments, only: [:create, :destroy]

  resources :users do
    member do
      get :jobs, :projects, :organizations
      match '/confirm/:token' => 'users#confirm', :as => :confirm
    end
  end

  resources :contacthistories, only: [:new, :create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/resetpswd', to: 'users#resetpswd'

  

end

app/models/user.rb
class User < ActiveRecord::Base
	
attr_accessible :botfisher, :fname, :lname, :phone, :birth_date, :email, :password, :password_confirmation, :bio, :id, :facebook, :twitter, :linkedin, :website, :confirmed

has_secure_password

before_save :create_remember_token
before_save :create_verification_token

valid_website_regex = /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix
validates :website, format: { with: valid_website_regex}
validates :fname, presence: true, length: { maximum: 50 }
validates :lname, presence: true, length: { maximum: 50 }
valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email,  presence:   true,
                   format:     { with: valid_email_regex },
                   uniqueness: { case_sensitive: false }
#validates :phone, presence: true
#validates :birth_date, presence: true
validates :password, length: { minimum: 6 }
validates :password_confirmation, presence: true

#implementing organization admins
has_many :contacthistories, dependent: :destroy
has_many :organizations, :through => :contacthistories

#implementing job applications
has_many :jobenrollments, dependent: :destroy
has_many :jobs, :through => :jobenrollments

#implementing posting of volunteering work
has_many :posted_projects, dependent: :destroy, class_name: "Project" #these are the POSTED projects

#împlementing application to volunteer work
has_many :projectenrollments, dependent: :destroy
has_many :projects, through: :projectenrollments

def has_applied?(job)
    jobenrollments.find_by_job_id(job.id)
end

def apply!(job)
	jobenrollments.create!(job_id: job.id)
end

def unapply!(job)
    jobenrollments.find_by_job_id(job.id).destroy
end

def has_volunteered?(project)
	projectenrollments.find_by_project_id(project.id)
end

def volunteer!(project)
	projectenrollments.create(project_id: project.id)
end

def unvolunteer!(project)
	projectenrollments.find_by_project_id(project.id).destroy
end

def current_organizations()
	if self.admin
		Organization.find(:all, :order => "LOWER(name)")
	else
		chs = contacthistories.all.select{ |c| c.current? }
		chs.collect{ |ch| ch.organization }
	end
end

def admin_of(org)
	current_organizations().include?(org) || (self.admin)
end

def proj_admin(proj)
	posted_projects.include?(proj) || (self.admin)
end

def confirm
	self.confirmed = true
end

private

	def create_remember_token
		self.remember_token = SecureRandom.urlsafe_base64
	end

	def create_verification_token
		self.verification_token = SecureRandom.urlsafe_base64
	end

end
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  fname           :string(255)
#  lname           :string(255)
#  birth_date      :date
#  email           :string(255)
#  phone           :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean
#  facebook        :string(255)
#  twitter         :string(255)
#  linkedin        :string(255)
#  bio             :string(1000)
#  website         :string(255)
#

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user, only: [:jobs, :projects, :organizations]
  before_filter :admin_user, only: [:index]
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @jobs = @user.jobs
    @posted_projects = @user.posted_projects
    @projects = @user.projects
    @job_suggestions = @user.jobs
  end

  def new
    @user = User.new
  end
  
  def create
    if params[:user][:botfisher].empty? 
      h = params[:user]
      h.delete("botfisher")
      @user = User.new(h)
      if @user.save
        @user.update_attribute(:confirmed, false)
        Notifications.welcome_email(@user).deliver
        #sign_in @user
        flash[:success] = "Welcome to GPEN, #{@user.fname}! Please confirm your account for full access to the GPEN website"
        redirect_to root_path
      else
        render 'new'
      end
    end
  end

  def confirm
    @user = User.find_by_verification_token(params[:token])
    @user.update_attribute(:confirmed, true) 
    if @user.confirmed == true  
      sign_in(@user)
      flash[:success] = "Your account has been successfully confirmed - You can now access the full GPEN database"
    else
      flash[:error] = "There has been a problem confirming your account "
    end 
    redirect_to root_path
  end

  def resetpswd
    if request.get?
      render 'resetpswd'
    end

    if request.post?
      @user = User.find_by_email(params[:user][:email])
      if @user.nil?
        flash[:error] = "The email address entered is not a GPEN account."
        redirect_to request.referer
      else
        new_pass = SecureRandom.urlsafe_base64
        @user.update_attributes(password: new_pass, password_confirmation: new_pass)
        flash[:notice] = "A new password has been sent to your email inbox !"
        Notifications.resetpswd_email(@user, new_pass).deliver
        redirect_to root_path
      end
    end

  end

  def jobs
    @user = User.find(params[:id])
    @jobs = @user.jobs
    render 'show_application'
  end

  def projects
    @user = User.find(params[:id])
    @projects= @user.projects
    render 'show_volunteering'
  end

  def organizations
    @user = User.find(params[:id])
    @organizations = @user.organizations
    render 'show_organizations'
  end

  def edit
    @user = User.find(params[:id])

    if !(!current_user.nil? && (current_user.admin == true || current_user.id == @user.id))
      flash[:error] = "You are not authorized to edit this user's profile."
      redirect_to @user
    end

  end

  def update
    if params[:user][:botfisher].empty? 
      h = params[:user]
      h.delete("botfisher")
      @user = User.find(params[:id])
      respond_to do |format|
        if @user.update_attributes(h)
          format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Profile successfully destroyed.' }
      format.json { head :no_content }
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, :html => {:class => "form-horizontal" } ) do |f| %>
    
    <% if @user.errors.any? %>

      <div class="alert alert-error">
        <h4 class="alert-heading"><%= pluralize(@user.errors.count, "error") %> prohibited your profile from being saved:</h4>

        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>


    <% end %>

    <fieldset>
      <div class="control-group">
        <%= f.label :fname, "First Name", class: "control-label" %>
        <div class="controls">
          <%= f.text_field :fname, class: "input-xlarge" %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :lname, "Last Name", class: "control-label" %>
        <div class="controls">
          <%= f.text_field :lname, class: "input-xlarge" %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :email, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :email, class: "input-xlarge" %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :phone, class: "control-label" %>
        <div class="controls">
          <%= f.text_field :phone, class: "input-xlarge" %>
        </div>
      </div>


      <div class="control-group">
            <%= f.label :birth_date, "Birth Date", class: "control-label" %>
            <div class="controls">
              <%= date_select 'user', "birth_date", {:start_year => Date.today.year-100, :end_year => Date.today.year}, {class: "span1"} %>
            </div>
          </div>

      <div class="control-group">
          <%= f.label :bio, class: "control-label" %>
          <div class="controls">
            <%= f.text_area :bio, :rows => 3, class: "input-xlarge" %>
                <p class="help-block">Tell us about yourself: who are you and what are your passions? What are you involved with in Philadelphia?</p>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :website, class: "control-label" %>
          <div class="controls">
            <div class="input-prepend">
                <%= f.text_field :website, class: "input-xlarge" %>
              </div>
              <p class="help-block">Please copy-paste the full website URL :</p>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :facebook, class: "control-label" %>
          <div class="controls">
            
            
            <div class="input-prepend">
                <span class="add-on">facebook.com/</span><%= f.text_field :facebook,class: "input-xlarge", placeholder: "Facebook Handle" %>
              </div>
              <p class="help-block">Please only type in your profile name for Facebook, not the entire URL.</p>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :twitter, class: "control-label" %>
          <div class="controls">
            <div class="input-prepend">
                <span class="add-on">twitter.com/</span><%= f.text_field :twitter,class: "input-xlarge", placeholder: "Twitter Handle" %>
              </div>
            <p class="help-block">Please only type in your profile name for Twitter, not the entire URL.</p>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :linkedin, class: "control-label" %>
          <div class="controls">
            

            <div class="input-prepend">
                <span class="add-on">linkedin.com/in/</span><%= f.text_field :linkedin,class: "input-xlarge", placeholder: "LinkedIn Handle" %>
              </div>
            <p class="help-block">Please only type in your profile name for LinkedIn, not the entire URL.</p>
          </div>
        </div>

      <div class="control-group">
        <%= f.label :password, class: "control-label" %>
        <div class="controls">
          <%= f.password_field :password, class: "input-xlarge" %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :password_confirmation, "Confirmation", class: "control-label" %>
        <div class="controls">
          <%= f.password_field :password_confirmation, class: "input-xlarge" %>
        </div>
      </div>

      <div style="display:none">
          <%= f.password_field :botfisher, class: "input-xlarge", placeholder: "parapapapa" %>
      </div>

      <div class="form-actions">

          <%= f.submit "Create Profile", class: "btn btn-primary" %>

      </div>
    </fieldset>
<% end %>

app/views/users/_job.html.erb
<tr>
    <td><%= job.title %></td>
    <td><%= job.organization.name %></td>
</tr>

app/views/users/edit.html.erb
<ul class="breadcrumb">
    <li>
      <a href="<%= root_path %>">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <%= link_to "Profile", @user %> <span class="divider">/</span>
    </li>
    <li class="active">Edit My Profile</li>
  </ul>



<div class="row"> 
    <div class="span12">
      <div class="well">
     
      <h1>Edit My Profile</h1>
      <hr>

      <%= form_for(@user, :html => {:class => "form-horizontal" } ) do |f| %>
          
          <% if @user.errors.any? %>

            <div class="alert alert-error">
              <h4 class="alert-heading"><%= pluralize(@user.errors.count, "error") %> prohibited your profile from being saved:</h4>

              <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>


          <% end %>

          <fieldset>
            <div class="control-group">
              <%= f.label :fname, "First Name", class: "control-label" %>
              <div class="controls">
                <%= f.text_field :fname, class: "input-xlarge" %>
              </div>
            </div>

            <div class="control-group">
              <%= f.label :lname, "Last Name", class: "control-label" %>
              <div class="controls">
                <%= f.text_field :lname, class: "input-xlarge" %>
              </div>
            </div>

            <div class="control-group">
              <%= f.label :email, class: "control-label" %>
              <div class="controls">
                <%= f.text_field :email, class: "input-xlarge" %>
              </div>
            </div>

            <div class="control-group">
              <%= f.label :phone, class: "control-label" %>
              <div class="controls">
                <%= f.text_field :phone, class: "input-xlarge" %>
              </div>
            </div>


            <div class="control-group">
                  <%= f.label :birth_date, "Birth Date", class: "control-label" %>
                  <div class="controls">
                    <%= date_select 'user', "birth_date", {:start_year => Date.today.year-100, :end_year => Date.today.year}, {class: "span1"} %>
                  </div>
                </div>

            <div class="control-group">
                <%= f.label :bio, class: "control-label" %>
                <div class="controls">
                  <%= f.text_area :bio, :rows => 3, class: "input-xlarge" %>
                      <p class="help-block">Tell us about yourself: who are you and what are your passions? What are you involved with in Philadelphia?</p>
                </div>
              </div>

              <div class="control-group">
                <%= f.label :website, class: "control-label" %>
                <div class="controls">
                  <div class="input-prepend">
                      <%= f.text_field :website, class: "input-xlarge" %>
                    </div>
                    <p class="help-block">Please copy-paste the full website URL :</p>
                </div>
              </div>

              <div class="control-group">
                <%= f.label :facebook, class: "control-label" %>
                <div class="controls">
                  
                  
                  <div class="input-prepend">
                      <span class="add-on">facebook.com/</span><%= f.text_field :facebook,class: "input-xlarge", placeholder: "Facebook Handle" %>
                    </div>
                    <p class="help-block">Please only type in your profile name for Facebook, not the entire URL.</p>
                </div>
              </div>

              <div class="control-group">
                <%= f.label :twitter, class: "control-label" %>
                <div class="controls">
                  <div class="input-prepend">
                      <span class="add-on">twitter.com/</span><%= f.text_field :twitter,class: "input-xlarge", placeholder: "Twitter Handle" %>
                    </div>
                  <p class="help-block">Please only type in your profile name for Twitter, not the entire URL.</p>
                </div>
              </div>

              <div class="control-group">
                <%= f.label :linkedin, class: "control-label" %>
                <div class="controls">
                  

                  <div class="input-prepend">
                      <span class="add-on">linkedin.com/in/</span><%= f.text_field :linkedin,class: "input-xlarge", placeholder: "LinkedIn Handle" %>
                    </div>
                  <p class="help-block">Please only type in your profile name for LinkedIn, not the entire URL.</p>
                </div>
              </div>

            <div class="control-group">
              <%= f.label :password, class: "control-label" %>
              <div class="controls">
                <%= f.password_field :password, class: "input-xlarge" %>
              </div>
            </div>

            <div class="control-group">
              <%= f.label :password_confirmation, "Confirmation", class: "control-label" %>
              <div class="controls">
                <%= f.password_field :password_confirmation, class: "input-xlarge" %>
              </div>
            </div>

            <div style="display:none">
                <%= f.password_field :botfisher, class: "input-xlarge", placeholder: "parapapapa" %>
            </div>

            <div class="form-actions">
                <%= f.submit "Update Profile", class: "btn btn-primary" %>
            </div>
          </fieldset>
      <% end %>


    </div><!--/well-->
    </div><!--/span12-->

</div><!--/row-->

app/views/users/index.html.erb




<div class="row">
  <div class="span12">
    <div class="well">
      <h1>Listing users</h1>
      <hr>
      <table class="table table-striped">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

      <% @users.each do |user| %>
        <tr>
          <td><%= user.fname %></td>
          <td><%= user.email %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Delete', user, confirm: 'Are you sure?', method: :delete %></td>
        </tr>
      <% end %>
      </table>

      <br />

      <%= link_to 'New User', signup_path %>
    </div><!--/well-->
  </div><!--/span12-->
</div><!--/row-->

app/views/users/new.html.erb
<ul class="breadcrumb">
        <li>
          <a href="<%= root_path %>">Home</a> <span class="divider">/</span>
        </li>
        <li class="active">Create New Profile</li>
      </ul>
      
      <div class="row">
         <div class="span12">
          

          <div class="hero-unit">
            <h1>Create New Profile</h1>
            <p>Create a profile on GPEN to apply for jobs, create organizations, and post volunteer projects.</p>
          </div>

          </div><!--/span12-->
          <div class="span12">
            <div class="well">
            <%= render 'form' %>
          </div><!--/well-->
          </div><!--/span12-->


          

        </div><!--/span-->

      </div><!--/row-->

app/views/users/resetpswd.html.erb
<% provide(:title, "Sign in") %>
<h1>Reset Password</h1>

<div class="row">
  <div class="span6 offset3">

    <%= form_for(:user, :url => resetpswd_path, :html => { :class => "form-horizontal" } ) do |f| %>
      <fieldset>
        <legend>Details</legend>
        <div class="control-group">
          <%= f.label :email, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :email, class: "input-xlarge" %>
          </div>
        </div>

        <div class="form-actions">
          <%= f.submit "Send me a new password", class: "btn btn-primary" %>
        </div>
      </fieldset>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<% @user ||= current_user %>
<% provide(:title, @user.fname + ' ' + @user.lname) %>
      <div class="row">
         <div class="span3">
          	<div class="well">
              
  		  		<h3><%= @user.fname %> <%= @user.lname %></h3>
            <% if @user.admin == true %>
              <span class="label label-inverse">GPEN Administrator</span><br>
            <% end %>
            <br>

            <h6>Joined</h6>
            <p><%= time_ago_in_words(@user.created_at) %> ago</p>

            <h6>Email</h6>
            <p><%= @user.email %></p>
            
            <% if !@user.website.nil? && !@user.website.empty? %>
              <h6>Website</h6>
              <p><%= link_to @user.website, @user.website %></p>
            <% end %>



            <% if !@user.twitter.nil? && !@user.twitter.empty? %>
              <%= link_to image_tag("icon-twitter.png", :class => "social-icon"), 'http://www.twitter.com/'+@user.twitter, :title => "Follow #{@user.fname} on Twitter", :rel => "tooltip" %>
            <% end %>
            <% if !@user.facebook.nil? && !@user.facebook.empty?  %>
              <%= link_to image_tag("icon-facebook.png", :class => "social-icon"), 'http://www.facebook.com/'+@user.facebook, :title => "Follow #{@user.fname} on Facebook", :rel => "tooltip" %>
            <% end %>
            <% if !@user.linkedin.nil? && !@user.linkedin.empty? %>
              <%= link_to image_tag("icon-linkedin.png", :class => "social-icon"), 'http://www.linkedin.com/in/'+@user.linkedin, :title => "Follow #{@user.fname} on LinkedIn", :rel => "tooltip" %>
            <% end %>

            <div class="clear"></div>
            	


            

            <% if (!current_user.nil? && (current_user.admin == true || current_user.id == @user.id)) %>
              <hr>
              <div class="btn-group">
                <button class="btn btn-primary">Admin Actions</button>
                <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Edit My Profile', edit_user_path(@user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Delete My Account', @user, confirm: 'Are you sure?', method: :delete %></li>
                </ul>
              </div> 
            <% end %>
            


  			 </div> <!--/well-->
        </div><!--/span3-->
        <div class="span9">

          <div class="row">
            <div class="span9">
              <div class="hero-unit">
                <h6>About <%= @user.fname %></h6>

                <p>
                  <% if !@user.bio.nil? %>
                    <%= @user.bio %>
                  <% else %>
                    This user has not added a bio yet.
                  <% end %>
                </p>
                <h6>User Stats</h6>
                <p>
                  <a href="<%= jobs_user_path(@user) %>">
                      <strong > <%= @user.jobs.count %> </strong> jobs applied to
                  </a> | 
                  <a href="<%= projects_user_path(@user) %>">
                      <strong > <%= @user.projects.count %> </strong> projects joined
                  </a>
                  | 

                  <a href="<%= organizations_user_path(@user) %>">
                      <strong > <%= @user.organizations.count %> </strong> organizations represented
                  </a>
                </p>
              </div>
            </div>
          </div>
        	<div class="row">
            <div class="span9">
              <div class="well">
                <div class="row-fluid">

                  <div class="span6">
                    
                    <h2>Jobs</h2>


                    <ul id="tab" class="nav nav-tabs">
                      <li class="active"><a href="#job-applications" data-toggle="tab">Applications</a></li>
                      <li class=""><a href="#job-suggestions" data-toggle="tab">Suggestions</a></li>
                    </ul>


                    <div id="job-tab-content" class="tab-content">
                      <div class="tab-pane fade active in" id="job-applications">
                        <table class="table table-striped">

                          <tbody>
                            <% @jobs.each do |job| %>
                              <tr>
                                <td>

                                  <h4><%= link_to job.title, job %></h4>
                                  <p><%= job.organization.name %></p>
                                </td>
                              </tr>
                            <% end %>


                          </tbody>
                        </table>

                      </div>
                      <div class="tab-pane fade" id="job-suggestions">
                        <div class="alert alert-block alert-info fade in">
                          <a class="close" data-dismiss="alert" href="#">×</a>
                          <h4 class="alert-heading">How Suggestions Work</h4>
                          <p>Job suggestions are generated based on information you add to your profile as well as previous organizations/jobs you have interacted with on GPEN. Below are what we have come up with for you!</p>
                        </div>

                        <table class="table table-striped">

                          <tbody>

                            <% if @job_suggestions.any? %>
                              <% @job_suggestions.each do |job_suggestion| %>
                                <tr>
                                  <td>

                                    <h4><%= link_to job_suggestion.title, job_suggestion %></h4>
                                    <p><%= job_suggestion.organization.name %></p>
                                  </td>
                                </tr>
                              <% end %>
                            <% end %>

                          </tbody>
                        </table>
                      </div>
                    </div>

                    
                  </div><!--/span6-->

                  <div class="span6">
                    <h2>Projects</h2>
                    
                    

                    <ul id="tab" class="nav nav-tabs">
                      <li class="active"><a href="#project-posted" data-toggle="tab">Posted</a></li>
                      <li class=""><a href="#project-attended" data-toggle="tab">Attended</a></li>
                      <li class=""><a href="#project-suggestions" data-toggle="tab">Suggestions</a></li>
                    </ul>


                    <div id="project-tab-content" class="tab-content">
                      <div class="tab-pane fade active in" id="project-posted">
                        <table class="table table-striped">
                          <tbody>

                            <%if @posted_projects.any?%>
                              <% @posted_projects.each do |posted_project| %>
                                <tr>
                                  <td>
                                    
                                    <h4><%= link_to posted_project.title, posted_project %></h4>
                                      <%= posted_project.organization.name unless posted_project.organization.nil?%></p>

                                  </td>
                                </tr>
                              <% end %>
                            <% end %>
                      
                          </tbody>
                        </table>
                      </div>
                      <div class="tab-pane fade" id="project-attended">
                        <table class="table table-striped">
                          <tbody>

                            <%if @projects.any?%>
                              <% @projects.each do |project| %>
                                <tr>
                                  <td>
                                    
                                    <h4><%= link_to project.title, project %> <%= "on "+project.start_date.strftime("%B %d, %Y") unless project.start_date.nil? %></h4>
                                      <% if project.organization.nil? %>
                                        <p> <%= project.user.fname %> </p>
                                      <% else %>
                                        <p> <%= project.organization.name %></p>
                                      <% end%>

                                  </td>
                                </tr>
                              <% end %>
                            <% end %>
                            
                          </tbody>
                        </table>
                      </div>
                      <div class="tab-pane fade" id="project-suggestions">
                        <div class="alert alert-block alert-info fade in">
                          <a class="close" data-dismiss="alert" href="#">×</a>
                          <h4 class="alert-heading">How Suggestions Work</h4>
                          <p>Project suggestions are generated based on information you add to your profile as well as previous organizations/jobs you have interacted with on GPEN. Below are what we have come up with for you!</p>
                        </div>
                      </div>
                    
                    </div>




                  </div><!--/span6-->
      

                </div><!--/row-fluid-->
              </div><!--/row-well-->
            </div><!--/span9-->
          </div><!--/row-->
        </div><!--/span-->

      </div><!--/row-->

app/views/users/show_application.html.erb





<div class="row">
   <div class="span12">
      <div class="well">
        <table class="table table-striped">
        <thead>
          <tr>
            <th>Job Title</th>
            <th>Job Organization</th>
          </tr>
        </thead>
        
        <tbody>
          <% if @jobs.any? %>
          

            <% @jobs.each do |job| %>
            <tr>
              <td><%= job.title %></td>
              <td><%= job.organization.name %></td>
            </tr>
          <% end %>




      <% end %>      
        </tbody>
      
</table>
    </div><!--/well-->
  </div><!--/span12-->
</div><!--/row-->



