config/routes.rb
GpenApp::Application.routes.draw do

  
  resources :searchonprojects

  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/profile', to: 'static_pages#profile'
  match '/create_org', to: 'static_pages#create_org'
  match '/browse_orgs', to: 'static_pages#browse_orgs'
  match '/list_orgs', to: 'static_pages#list_orgs'
  match '/org_profile', to: 'static_pages#org_profile'

  match '/create_job', to: 'static_pages#create_job'
  match '/browse_jobs', to: 'static_pages#browse_jobs'
  match '/list_jobs', to: 'static_pages#list_jobs'
  match '/single_job', to: 'static_pages#single_job'
  match '/single_project', to: 'static_pages#single_project'

  resources :jobs do
    get :resetcookies
  end

  resources :organizations do
    put :approve
    put :renew_three
    post :renew
    get :resetcookies
    member do
      get :contacthistories 
    end
  end

  resources :jobenrollments, only: [:create, :destroy]
  
  resources :projects do
    get :resetcookies
  end

  resources :projectenrollments, only: [:create, :destroy]

  resources :users do
    member do
      get :jobs, :projects, :organizations
      match '/confirm/:token' => 'users#confirm', :as => :confirm
    end
  end

  resources :contacthistories, only: [:new, :create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/resetpswd', to: 'users#resetpswd'

  

end

app/models/job.rb
class Job < ActiveRecord::Base
  STATUS=['Full-time', 'Part-time', 'Contract']
  AVAILABILITY=['Available', 'Unavailable']


  #one to many relationship with the organization model
  belongs_to :organization
  
  #implementing job applications
  has_many :jobenrollments, dependent: :destroy
  has_many :users, :through => :jobenrollments

  #implementing many-to-many between jobs and sectors
  has_many :jobsectors, dependent: :destroy
  has_many :sectors, through: :jobsectors

  validates :organization_id, :presence => true
  validates :title, :presence => true
  validates :status, :presence => true
  validates :availability, :presence => true

   
  # search methods will only display jobs that have orgs that have been approved and have not expired


  def self.filter(sector)
        sectorarray = sector.split(',')
        return Job.joins(:sectors, :organization)
                  .where('sectors.id' => sectorarray)
                  .where('organizations.approved = ? AND organizations.end_date > ?', true, Date.today)
                  .group('jobs.id')
                  .having('COUNT(jobs.id) = ?', sectorarray.size)
  end

  def self.search(search)
    if search.empty?
      # show all jobs that have orgs that have been approved and have not expired
      Job.joins(:organization).where('organizations.approved = ? AND organizations.end_date > ?', true, Date.today)
    else
      Job.joins(:organization)
          .where('organizations.approved = ? AND organizations.end_date > ?', true, Date.today)
          .where('UPPER(title) LIKE UPPER(?) OR UPPER(jobs.description) LIKE UPPER(?)', "%#{search}%", "%#{search}%")
    end
  end

  def self.search_and_filter(sector, search)
    sectorarray = sector.split(',')

    #first search results then filter them down by the sectors
    results = Job.joins(:sectors, :organization)
        .where('sectors.id' => sectorarray)
        .where('organizations.approved = ? AND organizations.end_date > ?', true, Date.today)
        .where('UPPER(title) LIKE UPPER(?) OR UPPER(jobs.description) LIKE UPPER(?)', "%#{search}%", "%#{search}%")
        .group('jobs.id')
        .having('COUNT(jobs.id) = ?', sectorarray.size)
    return results
  end




end

# == Schema Information
#
# Table name: jobs
#
#  id              :integer         not null, primary key
#  title           :string(255)
#  description     :text(255)
#  status          :string(255)
#  availability    :string(255)
#  organization_id :integer
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  start_date      :date
#  compensation    :string(255)
#

app/models/organization.rb
class Organization < ActiveRecord::Base
    require 'will_paginate/array'
    #### ASSOCIATION ####

 #one-to-many rel Job
  has_many :jobs, dependent: :destroy

 #one-to-many rel with Project
  has_many :projects, dependent: :destroy

 #many-to-many rel with Sector
  has_many :organizationsectors, dependent: :destroy
  has_many :sectors, :through => :organizationsectors

 #many-to-many rel with User (as admin)
  has_many :users, :through => :contacthistories
  has_many :contacthistories, dependent: :destroy
  
  
     #### VALIDATION ####

  validates :name, :presence => true
  
  valid_email_regex = /(^$)|\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: valid_email_regex }

#autre website regex : /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/ 
  valid_website_regex = /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix
  validates :website, format: { with: valid_website_regex }
  validates :email, :presence => true
  validates :address, :presence => true
  validates :city, :presence => true
  validates :state, :presence => true
  validates :zip, :presence => true
  validates :phone, :presence => true
  validates :description, :presence => true
  #validates :address2, :presence => true


  def current_admin?(user)
    user.current_organizations.include?(self)
  end

  def renew(months)
    # always renew from today's date, rather than from the current end_date
    self.end_date = Date.today + months.to_i.months

    # make sure the organization has been approved
    self.approved = true
  end

  def changeadmin(user_id, end_date)
    
  end

  #def self.search(search, page, sector)


     #sector : string of the form 'id1,id2,id3...'   
=begin      
      paginate :per_page => 10, 
               :page => page,
               :conditions => ['approved = ? AND end_date > ? AND (UPPER(name) LIKE UPPER(?) OR UPPER(description) LIKE UPPER(?) OR UPPER(city) LIKE UPPER(?) OR UPPER(state) LIKE UPPER(?) or UPPER(zip) LIKE UPPER(?))', true, Date.today,"%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%" , "%#{search}%"], 
                :order => 'name'
      end
=end


  def self.filter(sector)
        sectorarray = sector.split(',')
        #a = Organizationsector.find_all_by_sector_id(sectorarray)
        #b = a.collect {|orgsec| orgsec.organization}
        #return b

        return Organization.joins(:sectors)
                          .where('sectors.id' => sectorarray)
                          .group('organizations.id')
                          .where('approved = ? AND end_date > ?', true, Date.today) # get only orgs that have been approved and have not expired
                          .having('COUNT(organizations.id) = ?', sectorarray.size)

  end

  def self.search(search)
    if search.empty?
      Organization.where('approved = ? AND end_date > ?', true, Date.today) # get only orgs that have been approved and have not expired
    else
      Organization.find(:all, :conditions => ['approved = ? AND end_date > ? AND (UPPER(name) LIKE UPPER(?) OR UPPER(description) LIKE UPPER(?) OR UPPER(city) LIKE UPPER(?) OR UPPER(state) LIKE UPPER(?) or UPPER(zip) LIKE UPPER(?))', true, Date.today,"%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%" , "%#{search}%"])
    end
  end

  def self.search_and_filter(sector, search)
    sectorarray = sector.split(',')

    #first search results then filter them down by the sectors
    results = Organization.joins(:sectors)
                .where('sectors.id' => sectorarray)
                .where('approved = ? AND end_date > ?',  true, Date.today) # get only orgs that have been approved and have not expired
                .where('UPPER(name) LIKE UPPER(?) OR UPPER(organizations.description) LIKE UPPER(?) OR UPPER(city) LIKE UPPER(?) OR UPPER(state) LIKE UPPER(?) or UPPER(zip) LIKE UPPER(?)', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
                .group('organizations.id')
                .having('COUNT(organizations.id) = ?', sectorarray.size)

    return results

    # Amina's old filtering code, which finds UNION of filters, not INTERSECTION
    # searchresult.each do |o|
    #   sector_ids = o.sectors.collect {|sector| sector.id.to_s}
    #   sector_ids.each do |s| 
    #     if sectors.include?(s) 
    #       result = result << o
    #       break
    #     end
    #   end
    # end
    # return result

  end



STATES = [
    ['Alabama', 'AL'],
    ['Alaska', 'AK'],
    ['Arizona', 'AZ'],
    ['Arkansas', 'AR'],
    ['California', 'CA'],
    ['Colorado', 'CO'],
    ['Connecticut', 'CT'],
    ['Delaware', 'DE'],
    ['District of Columbia', 'DC'],
    ['Florida', 'FL'],
    ['Georgia', 'GA'],
    ['Hawaii', 'HI'],
    ['Idaho', 'ID'],
    ['Illinois', 'IL'],
    ['Indiana', 'IN'],
    ['Iowa', 'IA'],
    ['Kansas', 'KS'],
    ['Kentucky', 'KY'],
    ['Louisiana', 'LA'],
    ['Maine', 'ME'],
    ['Maryland', 'MD'],
    ['Massachusetts', 'MA'],
    ['Michigan', 'MI'],
    ['Minnesota', 'MN'],
    ['Mississippi', 'MS'],
    ['Missouri', 'MO'],
    ['Montana', 'MT'],
    ['Nebraska', 'NE'],
    ['Nevada', 'NV'],
    ['New Hampshire', 'NH'],
    ['New Jersey', 'NJ'],
    ['New Mexico', 'NM'],
    ['New York', 'NY'],
    ['North Carolina', 'NC'],
    ['North Dakota', 'ND'],
    ['Ohio', 'OH'],
    ['Oklahoma', 'OK'],
    ['Oregon', 'OR'],
    ['Pennsylvania', 'PA'],
    ['Puerto Rico', 'PR'],
    ['Rhode Island', 'RI'],
    ['South Carolina', 'SC'],
    ['South Dakota', 'SD'],
    ['Tennessee', 'TN'],
    ['Texas', 'TX'],
    ['Utah', 'UT'],
    ['Vermont', 'VT'],
    ['Virginia', 'VA'],
    ['Washington', 'WA'],
    ['West Virginia', 'WV'],
    ['Wisconsin', 'WI'],
    ['Wyoming', 'WY']
  ]
end

# == Schema Information
#
# Table name: organizations
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  description :text(1000)
#  address     :string(255)
#  city        :string(255)
#  state       :string(255)
#  zip         :string(255)
#  phone       :string(255)
#  website     :string(255)
#  feespaid    :boolean
#  end_date    :date
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#  address2    :string(255)
#  fax         :string(255)
#  facebook    :string(255)
#  twitter     :string(255)
#  linkedin    :string(255)
#  email       :string(255)
#

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  require 'will_paginate/array'
  before_filter :signed_in_user, only: [:create, :new, :update, :edit, :destroy]
 
  def index

    @searchtext = params[:search]
    @sectors = Sector.all
    @filters_ids = [] # array of ids of filters we are searching on
    @filters_string = "" # string of comma separated filters we are searching on
    @filters_obj = [] # array of objs of filters we are searching on

    # check to see if any cookies exist
    if !cookies[:filters_string].nil? && !cookies[:filters_string].empty?
      @filters_ids = cookies[:filters_string].split(',').collect { |stringid| stringid.to_i}
      @filters_string = cookies[:filters_string]
      @filters_obj = @filters_ids.collect {|id| Sector.find(id)}.uniq # used for showing labels of filters activated in view
    end
  
    # if this is a new submitted search, take in the params and overwrite any cookies
    if !params[:filters_string].nil?
      @filters_ids = params[:filters_string].split(',').collect { |stringid| stringid.to_i}
      @filters_string = params[:filters_string]
      cookies[:filters_string] = params[:filters_string] # replace cookies with current submitted filters
      @filters_obj = @filters_ids.collect {|id| Sector.find(id)}.uniq # used for showing labels of filters activated in view
    end

   #set up organizations search
   if @searchtext.nil? || @searchtext.empty?
      if @filters_string.nil? || @filters_string.empty?
        @organizations = Organization.search('') # no search, and no filters
      else
        @organizations = Organization.filter(@filters_string) # no search, and filters
      end
   else
     if @filters_string.nil? || @filters_string.empty? 
        @organizations = Organization.search(@searchtext) # search and no filters
     else 
        @organizations = Organization.search_and_filter(@filters_string, @searchtext) # search and filters
     end
   end


  end


  def resetcookies
    cookies[:filters_string] = nil
    redirect_to organizations_path
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])
    #@newadmin = @organization.contacthistories.new
    @newadmin = Contacthistory.new
    @newadmin.organization_id = @organization.id
    
    if @organization.approved == false || @organization.end_date < Date.today
        if !current_user.nil?
          if (!current_user.admin_of(@organization))
             redirect_to organizations_path 
             flash[:notice] = "This organization will be visible after it has been approved or renewed."
          end
        else 
            redirect_to organizations_path 
            flash[:notice] = "This organization will be visible after it has been approved or renewed."
        end
    end

    @date = @organization.end_date unless @organization.nil?
    @jobs = @organization.jobs
    @projects = @organization.projects
    @sectors = @organization.sectors
  end

  def renew
    @organization = Organization.find(params[:organization_id])
    if !current_user.admin_of(@organization) 
      redirect_to root_path 
    else
      @organization.renew(params[:months])
      
      if @organization.save
        flash[:success] = sprintf("Successfully renewed %s for %i months from today.", @organization.name, params[:months])
        redirect_to @organization
      else
        flash[:error] = sprintf("Error renewing organization. Please make sure this organization has all its required attributes filled in.")
        redirect_to @organization
      end
    end
  end



  def renew_three
    @organization = Organization.find(params[:organization_id])
    @organization.renew(3)
    
    if @organization.save
      flash[:success] = sprintf("Successfully renewed %s for %i months from today.", @organization.name, 3)
      redirect_to @organization
    else
      flash[:error] = sprintf("Error renewing organization. Please make sure this organization has all its required attributes filled in.")
      redirect_to @organization
    end
  end




  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
    redirect_to root_path unless current_user.admin_of(@organization)
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.create(params[:organization])
    @organization.approved = false
    @organization.sectors = Sector.find(params[:sector_ids]) if params[:sector_ids]
    if @organization.save
      Contacthistory.create(user_id: current_user.id, organization_id: @organization.id, start_date: Date.today, end_date: nil)
      flash[:success] = "Organization created! You are now an admin of this organization. Your organization will not show up in search results until it has been approved by the GPEN administration."
      redirect_to @organization
    else
      render 'organizations/new'
    end
  end

  def approve
    @organization = Organization.find(params[:organization_id])
    @organization.update_attributes(
      approved: true,
      end_date: Date.today + 3.months
    )
    @organization.contacthistories.each do |ch|
      ch.update_attributes(
        :start_date => Date.today
      )
    end
    
    if @organization.save
        flash[:success] = "You successfully temporaily approved: " + @organization.name + ". This organization will expire in 3 months. Add more time by using the Renew Membership function in the Admin Actions dropdown."
        redirect_to @organization
      else
        flash[:error] = sprintf("Error approving organization. Please make sure this organization has all its required attributes filled in.")
        redirect_to @organization
      end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])
    @organization.sectors = Sector.find(params[:sector_ids]) if params[:sector_ids]
    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization, :html => { :class => "form-horizontal" } ) do |f| %>
    <% if @organization.errors.any? %>
        <div class="alert alert-error">
        <h4 class="alert-heading"><%= pluralize(@organization.errors.count, "error") %> prohibited your profile from being saved:</h4>
          <ul>
          <% @organization.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <fieldset>
        <legend>Details</legend>
        <div class="control-group">
          <%= f.label :name, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :name, class: "input-xlarge" %>
                <p class="help-block">What is the title or name of your organization?</p>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :description, class: "control-label" %>
          <div class="controls">
            <%= f.text_area :description, :rows => 3, class: "input-xlarge" %>
                <p class="help-block">Describe the purpose and vision of your organization.</p>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :sectors, class: "control-label" %>
          <div class="controls">
            <%= select_tag("sector_ids[]", options_for_select(Sector.find(:all).collect { |sec| [sec.description, sec.id] }, @organization.sectors.collect { |sec| sec.id}), {:multiple=>true, :size=>6})%>
            <p class="help-block">Please select which sector(s) your organization falls into.</p>
              </div>

        </div>

        <legend>Location</legend>

            <div class="control-group">
          <%= f.label :address, "Address Line 1", class: "control-label" %>
          <div class="controls">
            <%= f.text_field :address, class: "input-xlarge" %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :address2, "Address Line 2", class: "control-label" %>
          <div class="controls">
            <%= f.text_field :address2, class: "input-xlarge" %>
          </div>
        </div>
        
        <div class="control-group">
          <%= f.label :city, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :city, class: "input-xlarge" %>
          </div>
        </div>

          <div class="control-group">
              <%= f.label :state, class: "control-label" %>
              <div class="controls">
                <%= f.select(:state, Organization::STATES) %>
              </div>
            </div>

            <div class="control-group">
              <%= f.label :zip, class: "control-label" %>
              <div class="controls">
                <%= f.text_field :zip, class: "input-xlarge" %>
              </div>
            </div>
        
        <legend>Contact Information</legend>
        <div class="control-group">
          <%= f.label :phone, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :phone, class: "input-xlarge" %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :email, class: "control-label" %>
          <div class="controls">
            <%= f.text_field :email, class: "input-xlarge" %>
          </div>
        </div>
      
      <div class="control-group">
          <%= f.label :website, class: "control-label" %>
          <div class="controls">
            <div class="input-prepend">
                <%= f.text_field :website, class: "input-xlarge" %>
              </div>
              <p class="help-block">Please copy-paste the full website URL :</p>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :facebook, class: "control-label" %>
          <div class="controls">
            
            
            <div class="input-prepend">
                <span class="add-on">facebook.com/</span><%= f.text_field :facebook,class: "input-xlarge", placeholder: "Facebook Handle" %>
              </div>
              <p class="help-block">Please only type in your profile name for Facebook, not the entire URL.</p>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :twitter, class: "control-label" %>
          <div class="controls">
            <div class="input-prepend">
                <span class="add-on">twitter.com/</span><%= f.text_field :twitter,class: "input-xlarge", placeholder: "Twitter Handle" %>
              </div>
            <p class="help-block">Please only type in your profile name for Twitter, not the entire URL.</p>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :linkedin, class: "control-label" %>
          <div class="controls">
            <div class="input-prepend">
                <span class="add-on">linkedin.com/in/</span><%= f.text_field :linkedin,class: "input-xlarge", placeholder: "LinkedIn Handle" %>
              </div>
            <p class="help-block">Please only type in your profile name for LinkedIn, not the entire URL.</p>
          </div>
        </div>


        <div class="form-actions">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      </fieldset>
    <% end %>

app/views/organizations/edit.html.erb
<ul class="breadcrumb">
        <li>
          <a href="<%= root_path %>">Home</a> <span class="divider">/</span>
        </li>
        <li>
          <a href="<%= organizations_path %>">Organizations</a> <span class="divider">/</span>
        </li>
        <li>
          <%= link_to @organization.name, @organization %> <span class="divider">/</span>
        </li>
        <li class="active">Edit Organization Profile</li>
      </ul>




		    <div class="row">
          <div class="span12">
            <div class="well">
            	<h1>Edit Organization Profile</h1>
			        <hr>

				        <%= render 'form' %>
            </div><!--/well-->
          </div><!--/span12-->
        </div><!--/row-->

app/views/organizations/index.html.erb
      <ul class="breadcrumb">
        <li>
          <a href="<%= root_path %>">Home</a> <span class="divider">/</span>
        </li>
        <li>
          <%= link_to "Organizations", organizations_path %>
        </li>
        <% unless @searchtext.nil? %> <span class="divider">/</span><li class="active">Search for '<%= @searchtext %>'</li><% end %>
      </ul>

<div class="row">
        <div class="span3">
          <div class="well sidebar-nav">
            
            <ul class="nav nav-list filters" id="search_filters">
              <h3>Filters</h3>
              <li class="nav-header">By Sector</li>
              <% @sectors.each do |sector| %>

                <li <% if !@filters_ids.nil? && (@filters_ids.include? sector.id)%> class="active" <% end %> id="<%= sector.id %>">
                  <a href="#"><%= sector.description %></a>
                </li>
              <% end %>
            </ul>


              

           

          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">

          <% if !current_user.nil? && current_user.admin == true %>
            <% @orgs_to_approve = Organization.where(approved: false) %>
            <% if @orgs_to_approve.any? %>  
              <div class="alert alert-info fade in">
                <a class="close" data-dismiss="alert">×</a>
                <strong>Admin notice:</strong> <%= pluralize(@orgs_to_approve.count, "organization") %> awaiting approval:
                
                <table class="table">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @orgs_to_approve.each do |ota| %>
                      <tr>  
                        <td>
                          <a href = "<%= organization_path(ota) %>"><%= ota.name %></a>
                        </td>
                        <td> <%= link_to('Approve for 3 Months', organization_approve_url(ota), :method => :put, class: "btn btn-success")%> </td> 
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            <% end %>


            <% @orgs_expired = Organization.where('approved = ? AND end_date < ?', true, Date.today) %>
            <% if @orgs_expired.any? %>  
              <div class="alert alert-info fade in">
                <a class="close" data-dismiss="alert">×</a>
                <strong>Admin notice:</strong> <%= pluralize(@orgs_expired.count, "organization") %> have expired:
                
                <table class="table">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @orgs_expired.each do |oe| %>
                      <tr>  
                        <td>
                          <a href = "<%= organization_path(oe) %>"><%= oe.name %></a>
                        </td>
                        <td> <%= link_to('Renew for 3 Months', organization_renew_three_url(oe), :method => :put, class: "btn btn-success")%> </td> 
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            <% end %>

            
          <% end %>

          <% if !current_user.nil? && current_user.organizations.where(approved: false).any? %>
            <div class="alert alert-info fade in">
              <a class="close" data-dismiss="alert">×</a>
              <strong>Notice:</strong> <%= pluralize(current_user.organizations.where(approved: false).count, 'organization') %> that you created are awaiting approval by GPEN staff. You will be notified via email when <% if current_user.organizations.where(approved:false).count > 1 %> they have <% else %> it has <% end %> been approved.
            </div>
          <% end %>
          <div class="hero-unit">

            
            <% if (@searchtext.nil? || @searchtext.empty?) && (@filters_string.nil? || @filters_string.empty?) %>

                <h1>Green Organizations</h1>
                <p>We are proud to say that we have <%= Organization.all.count %> (and counting!) green organizations listed on our website. Use the filters to the left or the search bar below to find organizations.</p>

            <% else %>

                <h2>Organization Results</h2>
                
                <% if !@filters_obj.nil? && !@filters_obj.empty? %>
                  <h6>filters</h6>
                    <% @filters_obj.each do |filterobject| %>
                        <span class="label label-info"><%= filterobject.description %></span> 
                    <% end %>
                <% end %>

            <% end %>

            <%= form_tag organizations_path, method: 'get', :id => 'search_orgs', class: 'form-search form-big-search' do %>
              <p>
                  <%= text_field_tag :search, params[:search], class: 'big-search-query' %>
                  
                  <%= hidden_field_tag :filters_string, @filters_string %>
                  <%= submit_tag "Search", class: 'btn btn-primary btn-big-search pull-right', name: 'nil'%>
              </p>
            <% end %>


            <% if !@filters_obj.nil? && !@filters_obj.empty? %>
              <%= link_to('Reset Filters', organization_resetcookies_url(1), :method => :get, class: "btn btn-success")%>
            <% end %>

            <% if signed_in?%><%= link_to 'Create New Organization', new_organization_path, class: "btn" %><% end %>

          </div>

          <div class="well">
            
      
      <% if @organizations.nil? || @organizations.empty? %>
        Your search shows no results. Reset filters and try another search.
      <% else %>  

        <h6><%= @organizations.length %> Search Results</h6>

        <table class="table table-striped">
          <thead>
            <tr>
              <th style="width: 60%">Title</th>
              <th style="width: 30%">Contact</th>
              <th style="width: 10%">Link</th>
            </tr>
          </thead>
          <tbody>

          
            <% @organizations.each do |organization| %>
              <% if !organization.nil? %>
                <tr>
                  <td>
                    
                  <h4><%= link_to(organization.name, organization, :class => "org-popover", :rel => "popover", "data-original-title" => organization.name, "data-content" => truncate(organization.description, :length => 200, :omission => '...')) %></h4>

                  <% if organization.sectors.any? %>                
                      <% organization.sectors.each do |sec| %>
                    <span class="label <% if !@filters_ids.nil? && (@filters_ids.include? sec.id)%> label-warning <% else %>label-success <% end %> "><%=sec.description%></span>
                      <% end %>
                    
                    <% end %>

                  <!--<p><%= truncate(organization.description, :length => 50, :omission => '...') %></p>-->


                  </td>
                  <td>
                    <address>
                      <%= organization.address %><br>
                      <%= organization.address2 if organization.address2 %>
                      <%= organization.city %>, <%= organization.state %> <%= organization.zip %><br>
                      <abbr title="Phone">P:</abbr> <%= organization.phone %><br>
                    </address>
                  </td>

                  
                  <td>
                    <%= link_to 'View', organization, class: "btn btn-small btn-success" %>
                    
                  </td>
                </tr>
                <% end %>
            <% end %>
          

          </tbody>
        </table>

        <% end %>
        



      

          </div><!--/well-->
        </div><!--/span-->
      </div><!--/row-->