config/routes.rb
GpenApp::Application.routes.draw do

  
  resources :searchonprojects

  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/profile', to: 'static_pages#profile'
  match '/create_org', to: 'static_pages#create_org'
  match '/browse_orgs', to: 'static_pages#browse_orgs'
  match '/list_orgs', to: 'static_pages#list_orgs'
  match '/org_profile', to: 'static_pages#org_profile'

  match '/create_job', to: 'static_pages#create_job'
  match '/browse_jobs', to: 'static_pages#browse_jobs'
  match '/list_jobs', to: 'static_pages#list_jobs'
  match '/single_job', to: 'static_pages#single_job'
  match '/single_project', to: 'static_pages#single_project'

  resources :jobs do
    get :resetcookies
  end

  resources :organizations do
    put :approve
    put :renew_three
    post :renew
    get :resetcookies
    member do
      get :contacthistories 
    end
  end

  resources :jobenrollments, only: [:create, :destroy]
  
  resources :projects do
    get :resetcookies
  end

  resources :projectenrollments, only: [:create, :destroy]

  resources :users do
    member do
      get :jobs, :projects, :organizations
      match '/confirm/:token' => 'users#confirm', :as => :confirm
    end
  end

  resources :contacthistories, only: [:new, :create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/resetpswd', to: 'users#resetpswd'

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
        <div class="footer-left">
          <div class="menu-footer clear">

            <ul id="menu-navigation-footer" class="menu">
              <li><a href="http://phillyecocity.com/">PhillyEcoCity</a></li>
              <li><a href="http://gpen.phillyecocity.com/">GPEN</a></li>
              <li><a href="http://phillyecocity.com/about/">About</a></li>
              <li><a href="http://phillyecocity.com/articles/">Articles</a></li>
              <li><a href="http://phillyecocity.com/events/">Events</a></li>
              <li><a href="http://gpen.phillyecocity.com/organizations">Organizations</a></li>
              <li><a href="http://gpen.phillyecocity.com/jobs">Jobs</a></li>
              <li><a href="http://gpen.phillyecocity.com/projects">Volunteer</a></li>
            </ul>
          </div>
          <div class="copyrights"> 
            <p><a href="http://phillyecocity.com">PhillyEcoCity</a> © 2011 All Rights Reserved         
            · Web Development by GPENonRails Team + <a title="balance through design." href="http://www.relativecommotion.com">Relative Commotion</a> 
            </p> 
          </div> 
        </div>
        <div class="footer-social"> 
          <div class="twitter-bird"></div>
        
          <ul class="social-links"> 
            <li class="feed"><a target="_blank" href="http://phillyecocity.com/feed/rss/"></a></li> 
            <li class="twitter"><a target="_blank" href="http://twitter.com/#!/phillyecocity"></a></li> 
            <li class="fb"><a target="_blank" href="http://www.facebook.com/pages/PhillyEcoCity/197186260342477"></a></li> 
            <li class="youtube"><a target="_blank" href="http://www.youtube.com/user/PhillyEcoCity"></a></li> 
          </ul>
          
          <div class="clear"></div>
           <div id="twitter_container">
             <ul id="twitter_update_list"></ul>
           </div>
        </div> 
        <div class="clear"></div> 
      </div> 



</footer>


      





<% if !signed_in? %>
<div id="signin-modal" class="modal hide fade">
    <div class="modal-header">
      <a class="close" data-dismiss="modal" >&times;</a>
      <h3>Sign In to Your Account</h3>
    </div>
    <div class="modal-body">
      <%= form_for(:session, :url => sessions_path, :html => { :class => "form-horizontal" } ) do |f| %>
            <fieldset>
              <div class="control-group">
                <%= f.label :email, class: "control-label" %>
                <div class="controls">
                  <%= f.text_field :email, class: "input-xlarge" %>
                </div>
              </div>

              <div class="control-group">
                <%= f.label :password, class: "control-label" %>
                <div class="controls">
                  <%= f.password_field :password, class: "input-xlarge" %>
                </div>
              </div>

            </fieldset>
  </div>
  <div class="modal-footer">
      <%= f.submit "Sign In", class: "btn btn-primary" %>
      <a href="#" class="btn" data-dismiss="modal">Close</a> 
  </div>
  <% end %>
</div>
<% end %>


<div id="job-apply-modal" class="modal hide fade">
    <div class="modal-header">
      <a class="close" data-dismiss="modal" >&times;</a>
      <h3>Apply to Job</h3>
    </div>
    <div class="modal-body">
      <form class="form-horizontal">
            <fieldset>
              <div class="control-group">
                <label class="control-label" for="disabledInput">Job Title</label>
                <div class="controls">
                  <input class="input-xlarge disabled" id="disabledInput" type="text" placeholder="Solar Panel Installer" disabled="">
                </div>
              </div>

              <div class="control-group">
                <label class="control-label" for="disabledInput">Organization Name</label>
                <div class="controls">
                  <input class="input-xlarge disabled" id="disabledInput" type="text" placeholder="EcoConsulting Firm" disabled="">
                </div>
              </div>


              <div class="control-group">
                <label class="control-label" for="cover">Cover Letter</label>
                <div class="controls">
                  <textarea class="input-xlarge" cols="40" id="cover" name="cover" rows="6"></textarea>
                  <p class="help-block">Describe the purpose and vision of your organization.</p>
                </div>
              </div>

              <div class="control-group">
                <label class="control-label" for="resume">Resume</label>
                <div class="controls">
                  <textarea class="input-xlarge" cols="40" id="resume" name="resume" rows="6"></textarea>
                  <p class="help-block">Please paste in a plain-text version of your resume, with any relevant experience.</p>
                </div>
              </div>

              <div class="control-group">
            <label class="control-label" for="optionsCheckbox"></label>
            <div class="controls">
              <label class="checkbox">
                <input type="checkbox" id="optionsCheckbox" value="option1">
                Send me a copy
              </label>
            </div>
          </div>

            </fieldset>
  </form>

  </div>
  <div class="modal-footer">
      <%= link_to "Send Application", "#", class: "btn btn-primary" %>
      <a href="#" class="btn" data-dismiss="modal">Close</a> 
  </div>
</div>

<script src="http://twitter.com/javascripts/blogger.js" type="text/javascript"></script>
<!--<script src="http://twitter.com/statuses/user_timeline/phillyecocity.json?callback=twitterCallback2&count=1" type="text/javascript"></script>-->  
<script src="http://api.twitter.com/1/statuses/user_timeline/phillyecocity.json?callback=twitterCallback2&count=1" type="text/javascript"></script> 
<!-- HELLO -->

app/views/layouts/_header.html.erb
<script type="text/javascript">
  jQuery(document).ready(function () {
    var randomNum = Math.ceil(Math.random()*5);
    $.vegas({
      src:"<%= image_path('bg/bg4.jpg') %>"
    });
    
  });
</script>




<header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" rel="tooltip" title="PhillyEcoCity: Greater Philadelphia Environment Network" href="http://phillyecocity.com">
             <%= image_tag("logo.png") %>
        </a>
        <div class="nav-collapse">
          <ul class="nav">

            <!--
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Users <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="<%= users_path %>">Browse Users</a></li>
              </ul>
            </li>
          -->


          <li>
            <a href="<%= root_path %>">GPEN</b></a>
          </li>
          

          <li>
              <a href="http://phillyecocity.com/about/">About</a>

              <!--
              <ul class="dropdown-menu">
                <li><a href="http://phillyecocity.com/about/vision/">Vision</a></li>
                <li class="divider"></li>
                <li><a href="http://phillyecocity.com/about/help/">Help us</a></li>
                <li class="divider"></li>
                 <li><a href="http://phillyecocity.com/about/histor/">History</a></li>
                <li class="divider"></li>
                 <li><a href="http://phillyecocity.com/about/contact/">Contact</a></li>
                <li class="divider"></li>
                 <li><a href="http://phillyecocity.com/about/shout-out/">Shout out</a></li>
                <li class="divider"></li>
                 <li><a href="http://phillyecocity.com/groups">Groups</a></li>
                <li class="divider"></li>
                 <li><a href="http://phillyecocity.com/members">Members</a></li>
                <li class="divider"></li>
                 <li><a href="http://phillyecocity.com/forums">Forums</a></li>
                <li class="divider"></li>
                 <li><a href="http://phillyecocity.com/activity">Activities</a></li>
                <li class="divider"></li>
              </ul>
            -->
            </li>

          <li>
              <a href="http://phillyecocity.com/articles/">Articles</b></a>
              
              <!--<ul class="dropdown-menu">
                <li><a href="http://phillyecocity.com/category/act-philly/">Act Philly</a></li>
                <li><a href="http://phillyecocity.com/category/think-globally/">Think Globally</a></li>
              </ul>-->
            </li>

          <li>
              <a href="http://phillyecocity.com/events/"> Events</a>
          </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Organizations <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="<%= organizations_path %>">Browse Organizations</a></li>
                <li class="divider"></li>
                <li><a href="<%= new_organization_path %>"><i class="icon-leaf"></i> Create Organization</a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Jobs <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="<%= jobs_path %>">Browse Jobs</a></li>
                <li class="divider"></li>
                <li><a href="<%= new_job_path %>"><i class="icon-lock"></i> Post Job for Org</a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Volunteer <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="<%= projects_path %>">Browse Projects</a></li>
                <li class="divider"></li>
                <li><a href="<%= new_project_path %>"><i class="icon-pencil"></i> Post Project</a></li>
              </ul>
            </li>

            <!--
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Eco Tips <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="http://phillyecocity.com/tools/carbon-footprint/">Carbon Footprint</a></li>
                <li class="divider"></li>
                <li><a href="http://phillyecocity.com/tools/water-footprint/">Water Footprint</a></li>
                <li class="divider"></li>
                 <li><a href="http://phillyecocity.com/tools/buying_less_stuff/">Buying Less Stuff</a></li>
                <li class="divider"></li>
                 <li><a href="http://phillyecocity.com/tools/values-based-shopping/">Values based Shopping</a></li>
                <li class="divider"></li>
                <li><a href=" http://phillyecocity.com/tools/recycling/">Recycling</a></li>
                <li class="divider"></li>
                 <li><a href="http://phillyecocity.com/the-meporter-app/">Citizen Journalism</a></li>
              </ul>
            </li>
            -->

            
          
          </ul>
          
          
          <ul class="nav pull-right">
          <!--   
            <li><form class="navbar-search pull-left" action="">
              <input id="search_bar_type" type="hidden" value="org">

            <input class="search-query span2" placeholder="Search Organizations" id="search_bar_input" size="16" type="text">

            </form>
          </li>
          
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-search icon-white" id="search_button" ></i> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a id="search_org" href="#">Search Organizations</a></li>
                <li><a id="search_job" href="#">Search Jobs</a></li>
                <li><a id="search_proj" href="#">Search Projects</a></li>
              </ul>
            </li>
          -->
            <li class="divider-vertical"></li>
            <% if signed_in? %>
              
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.fname %> <%= current_user.lname %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign Out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><a class="modal-btn" data-toggle="modal" href="#signin-modal" >Sign In</a></li>

            <% end %>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /navbar-inner -->
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>   
</head>
<body>

    <%= render 'layouts/header' %>

    <div class="container">

      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

    	<!-- 3 lines below removed by justin -->
      <!--  -->
		<!--<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p> -->
      <%= yield %>

      <%= debug(params) if Rails.env.development? %>
      
      
      
    </div>
    <%= render 'layouts/footer' %>

    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-39040091-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
  </body>
</html>